/**
 * ShopFlow Tracking System — Backward compatibility re-export
 * All logic has been moved to src/lib/tracking/ modules.
 * This file re-exports everything so existing imports continue to work.
 */
export {
  initPixel,
  trackEvent,
  flushEventQueue,
  enableDebug,
  sendAdvancedMatching,
  captureUTMs,
  getStoredUTMs,
  getFirstTouch,
  getLastTouch,
  getAttribution,
  getOrCreateSession,
  getSessionId,
  getDebugLog,
  clearDebugLog,
  getVisitCount,
  trackPageView,
  trackViewHome,
  trackViewCategory,
  trackViewContent,
  trackSelectProduct,
  trackSelectSize,
  trackAddToCart,
  trackBuyNow,
  trackInitiateCheckout,
  trackAddPaymentInfo,
  trackPurchase,
  trackClickWhatsApp,
  trackWhatsAppLead,
  trackOpenWholesalePage,
  trackWholesaleCTA,
  trackWholesaleLead,
  trackViewWholesaleCatalog,
  trackLead,
  trackBannerClick,
  trackCTA,
  trackSearch,
  trackCartAbandonment,
  trackVisitorType,
  trackCustomEvent,
  setupScrollTracking,
  setupTimeOnPage,
  setupProductPageEngagement,
} from "./tracking/index";

export type {
  TrackingProduct,
  TrackingCartItem,
  TrackingPurchase,
  TrackingCheckout,
  TrackingWhatsAppClick,
  TrackingWholesalePayload,
  TrackingBannerClick,
  TrackingCTAClick,
  TrackingSearch,
  TrackingSizeSelect,
  TrackingLead,
  DebugLogEntry,
  UTMData,
  SessionData,
  AttributionData,
} from "./tracking/index";
